// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KCALCORE_VERSION_H
#define KCALCORE_VERSION_H

#define KCALCORE_VERSION_STRING "5.117.0"
#define KCALCORE_VERSION_MAJOR 5
#define KCALCORE_VERSION_MINOR 117
#define KCALCORE_VERSION_PATCH 0
#define KCALCORE_VERSION ((5<<16)|(117<<8)|(0))

#endif
